apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: httpd
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80
  strategy:
    blueGreen: 
      activeService: nginx-svc
      previewService: httpd-svc
      autoPromotionEnabled: false

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpd
  name: httpd-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: httpd



---


apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
