apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: web
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80
  strategy:
    blueGreen: 
      activeService: nginx-svc
      previewService: httpd-svc
      autoPromotionEnabled: false

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: httpd-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web 



---


apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: nginx-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
