apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-bluegreen
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - name: http
        image: http
        ports:
        - containerPort: 80
  strategy:
    blueGreen: 
      activeService: green-svc
      previewService: blue-svc
      autoPromotionEnabled: false

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: green
  name: green-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: green

