apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blue
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80
  strategy:
    blueGreen: 
      activeService: green-svc
      previewService: blue-svc
      autoPromotionEnabled: false

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue
  name: green-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: blue

